/** Bindings, vars and secrets. Hand-written rather than generated by `wrangler types`:
 *  RateLimit and ExecutionContext.cache are already in @cloudflare/workers-types. */
export interface Env {
  MEOWMAP_DB: D1Database;
  PHOTOS: R2Bucket;

  RL_MUTATE_IP: RateLimit;
  RL_MUTATE_DEVICE: RateLimit;
  RL_PASS_IP: RateLimit;
  RL_BULK_IP: RateLimit;

  // [vars]
  ALLOWED_ORIGIN: string;
  JWT_ISS: string;
  JWT_AUD: string;
  PASS_TTL_DAYS: string;
  PASS_RENEW_WITHIN_DAYS: string;
  TURNSTILE_SITE_KEY: string;

  // secrets, pushed by CI
  TURNSTILE_SECRET_KEY: string;
  PASS_SIGNING_SECRET: string;
}

/* 'fled' was a third option, cut after device testing. The validator has rejected it
 * since, so the type had been lying; migration 003 normalises any leftover row. */
export type Petted = 'yes' | 'no';
export type SizeTag = 'kitten' | 'adult' | 'chonk';
export type LocationSource = 'exif' | 'device' | 'manual';
export type PhotoVariant = 'full' | 'thumb';

/** A sighting as it crosses the wire. `clientId` MUST be echoed on every read: the
 *  offline client dedupes its pending pins against it, and without it the map
 *  double-pins after every upload. */
export interface SightingDto {
  id: number;
  clientId: string;
  catId: number | null;
  lat: number;
  lon: number;
  locationSource: LocationSource;
  accuracyM: number | null;
  seenAt: number;
  note: string | null;
  photoFull: string;
  photoThumb: string;
  photoW: number;
  photoH: number;
  createdAt: number;
  updatedAt: number;
}

export interface CatDto {
  id: number;
  name: string | null;
  notes: string | null;
  /* Coat, size and petted describe the ANIMAL, so they live here rather than on each
   * sighting — see migration 003. */
  coat: string[];
  size: SizeTag | null;
  petted: Petted | null;
  createdAt: number;
  updatedAt: number;
}

export interface SightingRow {
  id: number;
  client_id: string;
  cat_id: number | null;
  lat: number;
  lon: number;
  location_source: string;
  accuracy_m: number | null;
  seen_at: number;
  note: string | null;
  photo_full: string;
  photo_thumb: string;
  photo_w: number;
  photo_h: number;
  created_at: number;
  updated_at: number;
}

export interface CatRow {
  id: number;
  name: string | null;
  notes: string | null;
  coat: string | null;
  size: string | null;
  petted: string | null;
  created_at: number;
  updated_at: number;
}

/** The R2 cost breaker's state, plus the ETag source. Single row, id = 1. */
export interface AppMeta {
  data_version: number;
  r2_bytes: number;
  r2_objects: number;
  r2_reads_est: number;
  usage_day: number;
  uploads_today: number;
  reads_month: number;
}

/** Thrown for anything the caller did wrong. Carries its own status so the top-level
 *  handler never has to match on message substrings — spirit-tracker-api does that and
 *  it is both fragile and leaks internal error text on a 500. */
export class HttpError extends Error {
  readonly status: number;
  readonly outcome: string;
  constructor(status: number, message: string, outcome = 'invalid') {
    super(message);
    this.name = 'HttpError';
    this.status = status;
    this.outcome = outcome;
  }
}
